{{- if and .Values.storage.internal.enabled .Values.storage.internal.persistence.enabled (not .Values.storage.internal.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.minio.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - {{ .Values.storage.internal.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.internal.persistence.size | quote }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.storage.internal.persistence.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
