{{- if and (not .Values.collabora.existingSecret) .Values.collabora.enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-collabora" (include "opencloud.fullname" .)) }}
{{- $password := "" }}
{{- if $secret }}
  {{- $password = index $secret.data "password" | b64dec }}
{{- else if .Values.collabora.admin.password }}
  {{- $password = .Values.collabora.admin.password }}
{{- else }}
  {{- $password = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-collabora
type: Opaque
stringData:
  username: {{ .Values.collabora.admin.username }}
  password: {{ $password }}
{{- end }}
