{{- if and .Values.identityProvider.keycloak.postgres.enabled .Values.identityProvider.keycloak.enabled (and .Values.identityProvider.keycloak.postgres.persistence.enabled (not .Values.identityProvider.keycloak.postgres.persistence.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.postgres.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - {{ .Values.identityProvider.keycloak.postgres.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.identityProvider.keycloak.postgres.persistence.size | quote }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.identityProvider.keycloak.postgres.persistence.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
