{{- if and .Values.identityProvider.keycloak.enabled (not .Values.identityProvider.keycloak.postgres.existingSecret) .Values.identityProvider.keycloak.postgres.enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "opencloud.postgres.fullname" .) }}
{{- $password := "" }}
{{- if $secret }}
  {{- $password = index $secret.data "password" | b64dec }}
{{- else if .Values.identityProvider.keycloak.postgres.password }}
  {{- $password = .Values.identityProvider.keycloak.postgres.password }}
{{- else }}
  {{- $password = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.postgres.fullname" . }}
type: Opaque
stringData:
  username: {{ .Values.identityProvider.keycloak.postgres.user }}
  password: {{ $password }}
{{- end }}
