{{- if .Values.identityProvider.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: {{ .Values.identityProvider.keycloak.replicas }}
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: keycloak
          image: {{ include "opencloud.image" (dict "Chart" .Chart "imageValues" .Values.identityProvider.keycloak.image "global" .Values.global) | quote }}
          imagePullPolicy: {{ include "opencloud.image.pullPolicy" (dict "pullPolicy" .Values.identityProvider.keycloak.image.pullPolicy "global" .Values.global) }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh", "/opt/keycloak/bin/docker-entrypoint-override.sh"]
          args:
            - "start"
            - "--http-enabled=true"
            - "--proxy-headers=xforwarded"
            - "--hostname=https://{{ include "opencloud.keycloak.domain" . }}"  # Explicitly set the external hostname
            - "--spi-connections-http-client-default-disable-trust-manager={{ .Values.opencloud.insecure }}"
            - "--import-realm"
          env:
            - name: OC_DOMAIN
              value: {{ include "opencloud.domain" . }}
            - name: KC_HOSTNAME_URL
              value: "https://{{ include "opencloud.keycloak.domain" . }}"  # Ensure the URL includes the https:// scheme
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ include "opencloud.postgres.fullname" . }}:5432/{{ .Values.identityProvider.keycloak.postgres.database }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.identityProvider.keycloak.postgres.existingSecret }}
                          {{ .Values.identityProvider.keycloak.postgres.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.postgres.fullname" . }}
                        {{- end }}
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.identityProvider.keycloak.postgres.existingSecret }}
                          {{ .Values.identityProvider.keycloak.postgres.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.postgres.fullname" . }}
                        {{- end }}
                  key: password
            - name: KC_FEATURES
              value: impersonation
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.identityProvider.keycloak.existingSecret }}
                          {{ .Values.identityProvider.keycloak.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.keycloak.fullname" . }}
                        {{- end }}
                  key: adminUser
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.identityProvider.keycloak.existingSecret }}
                          {{ .Values.identityProvider.keycloak.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.keycloak.fullname" . }}
                        {{- end }}
                  key: adminPassword
            {{- if .Values.identityProvider.keycloak.cors.enabled }}
            - name: KC_SPI_CORS_ENABLED
              value: "true"
            {{- if .Values.identityProvider.keycloak.cors.allowAllOrigins }}
            - name: KC_SPI_CORS_ORIGINS
              value: "*"
            {{- else }}
            - name: KC_SPI_CORS_ORIGINS
              value: {{ join "," .Values.identityProvider.keycloak.cors.origins | quote }}
            {{- end }}
            - name: KC_SPI_CORS_METHODS
              value: {{ .Values.identityProvider.keycloak.cors.methods | quote }}
            - name: KC_SPI_CORS_HEADERS
              value: {{ .Values.identityProvider.keycloak.cors.headers | quote }}
            - name: KC_SPI_CORS_EXPOSED_HEADERS
              value: {{ .Values.identityProvider.keycloak.cors.exposedHeaders | quote }}
            - name: KC_SPI_CORS_ALLOW_CREDENTIALS
              value: {{ .Values.identityProvider.keycloak.cors.allowCredentials | quote }}
            - name: KC_SPI_CORS_MAX_AGE
              value: {{ .Values.identityProvider.keycloak.cors.maxAge | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: script
              mountPath: /opt/keycloak/bin/docker-entrypoint-override.sh
              subPath: docker-entrypoint-override.sh
            - name: realm-config
              mountPath: /opt/keycloak/data/import-dist/opencloud-realm.json
              subPath: opencloud-realm.json
          resources:
            {{- toYaml .Values.identityProvider.keycloak.resources | nindent 12 }}
      volumes:
        - name: script
          configMap:
            name: {{ include "opencloud.keycloak.fullname" . }}-script
            defaultMode: 0755
        - name: realm-config
          configMap:
            name: {{ include "opencloud.keycloak.fullname" . }}-realm
{{- end }}
