{{- if and (not .Values.opencloud.smtp.existingSecret) .Values.opencloud.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-smtp
type: Opaque
stringData:
  smtpUser: {{ .Values.opencloud.smtp.username }}
  smtpPassword: {{ .Values.opencloud.smtp.password }}
{{- end }}
---
{{- if and (not .Values.identityProvider.internal.existingSecret) (not (or .Values.identityProvider.keycloak.enabled .Values.identityProvider.external.enabled)) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "opencloud.opencloud.fullname" .) }}
{{- $adminPassword := "" }}
{{- if $secret }}
  {{- $adminPassword = index $secret.data "adminPassword" | b64dec }}
{{- else if .Values.identityProvider.internal.adminPassword }}
  {{- $adminPassword = .Values.identityProvider.internal.adminPassword }}
{{- else }}
  {{- $adminPassword = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}
type: Opaque
stringData:
  adminPassword: {{ $adminPassword }}
{{- end }}
---
{{- if and (not .Values.storage.external.existingSecret) .Values.storage.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-s3
type: Opaque
stringData:
  accessKey: {{ .Values.storage.external.accessKey }}
  secretKey: {{ .Values.storage.external.secretKey }}
{{- end }}